### ISSUE TITLE
Link broken in README

### ISSUE THREAD

**Issue by premasagar** [ccoffing/OcherBook#48]
The link to Hack you Kobo in the README 404's

**Comment by chocoelho** [comment]
I think that's the correct link: http://uscoffings.net/tech/embedded/kobo-touch/#access

**Comment by ccoffing** [comment]
Yes, thank you, I will update.

FWIW, I know I have been letting this project languish.  I'm still committed to the idea.  But I started this project too deep and too specific.  Insanely fun but not sustainable at that depth.  I haven't been "hacking kobo" recently because I need to build a basic, efficient, flexible reader first, and only then bring it to Kobo (at whatever level -- raw fb or Qt, that's a later decision).

I am working on a rebooted codebase (more standardized: autoconf, C++11, not trying to unify event loops).  I just need to figure out how -- or if -- these projects relate.
